server:
  port: 8087

spring:
  application:
    name: AUTH-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

openapi:
  service:
    title: order-service doc
    version: 1.0.0
    url: http://localhost:8080 #Gateway

springdoc:
  api-docs:
    path: /auth-service/v3/api-docs
  swagger-ui:
    path: /auth-service/swagger-ui.html
    enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
