server:
  port: 8087

spring:
  application:
    name: AUTH-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        security: DEBUG
